name: "Umbrel App Linter"
author: "Josua Frank"
description: "This is a small GitHub Action for linting umbrelOS apps"
runs:
  using: "node20"
  main: "dist/index.js"
inputs:
  github-token:
    description: "GitHub token to access the repository"
    required: false
    default: ${{ github.token }}
  base:
    description: "The base commit or branch to compare"
    required: false
  head-sha:
    description: "The head commit sha to compare"
    required: false
outputs:
  errors:
    description: "The number of errors found"
  warnings:
    description: "The number of warnings found"
  infos:
    description: "The number of infos found"
  results:
    description: "The raw results of the linter"
branding:
  icon: "umbrella"
  color: "blue"
