name: Create release on version change

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: check
        uses: EndBug/version-check@v2
        with:
          diff-search: true
      - if: steps.check.outputs.changed == 'false'
        id: get_latest_tag
        run: |
          git fetch --tags
          echo "LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT
      - if: steps.check.outputs.changed == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: Umbrel App Linter v${{ steps.check.outputs.version }}
          tag_name: v${{ steps.check.outputs.version }}
          body: "**Full Changelog**: https://github.com/sharknoon/umbrel-app-linter-action/compare/${{ steps.get_latest_tag.outputs.LATEST_TAG }}...v${{ steps.check.outputs.version }}"
